services:
  mongodb:
    image: mongo:latest
    container_name: mern-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mern-pokemons
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
